@port=3070


###
GET http://localhost:{{port}}/


###
GET http://localhost:{{port}}/api/
###
GET http://localhost:{{port}}/api/v1/meals

###
GET http://localhost:{{port}}/meals/1

###
POST http://localhost:{{port}}/api/v1/meals/
Content-Type: application/json
some-other-header: with my very personal information

{
    "name": "Pizza",
    "calories": 400
}

###
DELETE http://localhost:{{port}}/api/v1/meals/1


###
POST http://localhost:{{port}}/api/v1/meals/seed

###
POST http://localhost:{{port}}/api/v1/workouts/seed

###
POST http://localhost:{{port}}/api/v1/users/seed

###
DELETE http://localhost:{{port}}/api/v1/meals/64514cf95780cb768acac2fa
